// Custom Unity config — exists solely to prevent PlatformIO's autogenerated
// Arduino unity_config.cpp from calling Serial.end() in unityOutputComplete(),
// which on ESP32-C6 triggers HWCDC::deinit() and yanks USB D+/D- low, leaving
// the device unenumerable until hard reset.
//
// PIO detects this file and skips auto-generation of unity_config.{h,cpp},
// using ours instead. See platformio/test/runners/unity.py.
// https://github.com/platformio/platformio-core/issues/5359

#ifndef UNITY_CONFIG_H
#define UNITY_CONFIG_H

// MinGW-w64 UCRT toolchain (Strawberry Perl) defines setjmp as a 2-arg
// intrinsic, but PlatformIO's native env doesn't link the CRT import lib
// that resolves _setjmp. Excluding setjmp is safe here — Unity's
// TEST_PROTECT() becomes a no-op, and all assertion macros work normally.
#ifndef UNITY_EXCLUDE_SETJMP_H
#define UNITY_EXCLUDE_SETJMP_H
#endif

#ifdef __cplusplus
extern "C" {
#endif

void unityOutputStart(unsigned long);
void unityOutputChar(unsigned int);
void unityOutputFlush(void);
void unityOutputComplete(void);

#define UNITY_OUTPUT_START()    unityOutputStart((unsigned long) 115200)
#define UNITY_OUTPUT_CHAR(c)    unityOutputChar(c)
#define UNITY_OUTPUT_FLUSH()    unityOutputFlush()
#define UNITY_OUTPUT_COMPLETE() unityOutputComplete()

#ifdef __cplusplus
}
#endif

#endif /* UNITY_CONFIG_H */
